#!/bin/bash 

# Welcome message
echo "This is an initialisation script for eVision Linux."
echo "It should be called only once on a fresh yocto image."

read -p "Should we continue? [y/n]:" -n 1 -r
echo    # move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then

    # add openvpn to startup
    echo "Adding openvpn for autostartup"
    ln -s /etc/init.d/openvpn /etc/rc5.d/S91openvpn
    ln -s /etc/init.d/openvpn /etc/rc3.d/S91openvpn
    sleep 1
    
    echo "Setting wifi password"
    wpa_passphrase Freescale FreescaleCUP > /etc/wpa_supplicant.conf
    sleep 1
    
    echo "Adding 8.8.8.8 nameserver"
    echo "prepend domain-name-servers 8.8.8.8;" >> /etc/dhcp/dhclient.conf
    /etc/init.d/networking restart
    sleep 1
    
    echo "Setting uptime tracker"
    crontab -l | { cat; echo "*/1 * * * * date >> /var/timelog"; } | crontab -
    sleep 1
    
    echo "Configuring timezone"
    ln -sf /usr/share/zoneinfo/EET /etc/localtime
    sleep 1
    
    echo "Configuring time sincronization"
    echo "driftfile /etc/ntp.drift" >  /etc/ntp.conf
    echo "server 0.ro.pool.ntp.org" >> /etc/ntp.conf
    echo "server 1.ro.pool.ntp.org" >> /etc/ntp.conf
    echo "server 2.ro.pool.ntp.org" >> /etc/ntp.conf
    echo "server 3.ro.pool.ntp.org" >> /etc/ntp.conf
    echo "server  127.127.1.0" 		>> /etc/ntp.conf
	echo "fudge   127.127.1.0 stratum 10" >> /etc/ntp.conf
	echo "restrict default" >> /etc/ntp.conf
	ntpd -q -g -x
	sleep 1
    
    echo "Getting application from github"
    git clone https://github.com/izzi/app-evision.git /home/root/app
    sleep 1
fi
